# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'LoveCounterApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoveCounterApp
  pod 'DeviceKit', '~> 2.0'
  pod 'SnapKit', '~> 4.0.0'
  
  #pod 'RxSwift'
  #pod 'RxCocoa'
  #pod 'ReactorKit'
  #pod 'RxFlow'
  #pod 'Then'

end
